language: ruby
rvm:
  - 2.4.2
before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.9.deb
  - sudo dpkg -i elasticsearch-5.6.9.deb
  - sudo systemctl start elasticsearch.service
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec
branches:
  only:
    - master
env:
  FB_APP_ID=test
  FB_APP_SECRET=secret
  S3_BUCKET_NAME=s3_aws_bucket
  AWS_ACCESS_KEY_ID=aws_id
  AWS_SECRET_ACCESS_KEY=aws_secret
  AWS_REGION=aws_region
