language: ruby
rvm:
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - bundle install
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://localhost:9200
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec
services:
  - mysql
branches:
  only:
    - master
env:
  ES_VERSION=6.8.2
  ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  ELASTIC_SEARCH_HOST=http://localhost:9200
  FB_APP_ID=test
  DBHOST=localhost
  DBUSER=root
  FB_APP_SECRET=secret
  S3_BUCKET_NAME=s3_aws_bucket
  AWS_ACCESS_KEY_ID=aws_id
  AWS_SECRET_ACCESS_KEY=aws_secret
  AWS_REGION=aws_region
