version: '3'

services:
  api:
    build: .
    container_name: api
    ports:
      - 3000:3000
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
      - elastic_search
      - redis_cache
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: postgres
    command: --default-authentication-plugin=postgres_native_password
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: unless-stopped

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - 6379:6379
    volumes:
      - redis_cache_volume:/var/lib/redis

  elastic_search:
    image: elasticsearch:7.16.1
    container_name: elastic_search
    ports:
      - 8004:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elastic_search_volume:/var/lib/elastic_search

volumes:
  postgres_volume: {}
  redis_cache_volume: {}
  elastic_search_volume: {}
