default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['DBHOST'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>

development:
  <<: *default
  database: kardies_development

test:
  <<: *default
  database: kardies_test

production:
  <<: *default
  database: kardies_production
