personalities:
  ISTJ:
    Χαρακτήρας ήσυχος, σοβαρός, αξιόπιστος. Πρακτικός, πραγματικός, ρεαλιστικός και υπεύθυνος.
    Αποφασίζει λογικά τα σχέδια του και τα καταφέρνει αργά και σταθερά
    ανεξάρτητα από περισπασμούς. Παίρνει ευχαρίστηση όταν τα πάντα είναι τακτοποιημένα
    και οργανωμένα. Εκτιμά τις παραδόσεις και την αξιοπιστία.
  ISFJ:
    Χαρακτήρας ήσυχος, φιλικός, υπεύθυνος και ευσυνείδητος. Σταθερός στην εκπλήρωση των υποχρεώσεών του.
    Κοιτά τις λεπτομέρειες, και ειναι ακριβής. Πιστός, προσεκτικός, παρατηρεί και
    θυμάται λεπτομέρειες σχετικά με τους ανθρώπους που είναι σημαντικοί για αυτόν,
    τον νοιάζει για το πώς αισθάνονται οι άλλοι. Προσπαθεί να δημιουργεί ένα
    ομαλό και αρμονικό περιβάλλον στην εργασία και στο σπίτι.
  INFJ:
    Χαρακτήρας που αναζητά το νόημα των πραγμάτων και των σχέσεων.
    Θέλει να καταλαβαίνει τους ανθρώπους και γενικά είναι διορατικός.
    Ευσυνείδητος και αφοσιωμένος στις αξίες του.
    Έχει ένα καθαρό όραμα για την καλυτέρευση του κοινού καλού.
    Οργανωμένος και αποφασιστικός στην υλοποίηση των στόχων του.
  INTJ:
    Χαρακτήρας που έχει πρωτοποριακές ιδέες και μεγάλη αφοσίωση για την εφαρμογή και την επίτευξη των στόχων του.
    Καταλαβαίνει γρήγορα γεγονότα και αναπτύσσει επεξηγηματικές λεπτομέρειες για τα πάντα.
    Όταν έχει δεσμευτεί να οργανώσει μια δουλειά την φέρνει εις πέρας.
    Σκεπτικός και ανεξάρτητος, περιμένει πολλά από τον εαυτό του και από τους άλλους.
  ISTP:
    Χαρακτήρας ανεκτικός και ευέλικτος, ήσυχος παρατηρητής μέχρι να εμφανιστεί κάποιο πρόβλημα
    και στη συνέχεια ενεργεί γρήγορα για να βρει εφαρμόσιμες λύσεις.
    Είναι αναλυτικός και καταλαβαίνει τον πυρήνα των προβλημάτων.
    Ενδιαφέρεται για αιτίες και συνέπειες, οργανώνει τα θέματα του χρησιμοποιώντας λογική.
  ISFP:
    Χαρακτήρας ήσυχος, φιλικός, ευαίσθητος και ευγενικός. Απολαμβάνει την παρούσα στιγμή.
    Θέλει να έχει το δικό του χώρο και να εργάζεται με το δικό του ωράριο.
    Πιστός και αφοσιωμένος στις αξίες του και στους ανθρώπους που είναι σημαντικοί για αυτόν.
    Αντιπαθεί διαφωνίες και συγκρούσεις, δεν επιβάλλει τις απόψεις ή τις αξίες του σε άλλους.
  INFP:
    Χαρακτήρας ιδεαλιστικός, πιστός στις αξίες του και σε ανθρώπους που είναι σημαντικοί για αυτόν.
    Θέλει να έχει μια ζωή που είναι σύμφωνη με τις αξίες του.
    Έχει περιέργια για την ζωή και είναι γρήγορος στο να δράξει ευκαιρίες.
    Προσπαθεί να κατανοήσει τους ανθρώπους και να τους βοηθήσει να ανακαλύψουν τις δυνατότητές τους.
    Προσαρμοστικός, ευέλικτος και αποδεκτικός εκτός αν απειλούνται οι αξίες του.
  INTP:
    Χαρακτήρας που προσπαθεί να αναπτύσσει λογικές εξηγήσεις για όλα όσα τον ενδιαφέρουν.
    Θεωρητικός και αφηρημένος, τον ενδιαφέρουν περισσότερο οι ιδέες παρά οι κοινωνικές συναναστροφές.
    Ήσυχος, εσωστρεφής και προσαρμοστικός. Έχει ασυνήθιστη ικανότητα να εστιάζει σε βάθος
    όταν λύνει προβλήματα πάνω σε θέματα που τον ενδιαφέρουν. Σκεπτικός και πάντα αναλυτικός.
  ESTP:
    Χαρακτήρας ευέλικτος και ανεκτικός, υιοθετεί μια ρεαλιστική προσέγγιση επικεντρωμένη στα άμεσα αποτελέσματα.
    Οι θεωρίες και οι εννοιολογικές εξηγήσεις τον κουράζουν, θέλει να δρα ενεργά για να λύσει κάποιο πρόβλημα.
    Επικεντρώνεται στο εδώ και τώρα, αυθόρμητος, απολαμβάνει την κάθε στιγμή όταν είναι με άλλους.
    Απολαμβάνει τις υλικές ανέσεις και το στυλ. Μαθαίνει καλύτερα μέσω των πράξεων.
  ESFP:
    Χαρακτήρας εξωστρεφής, φιλικός και αποδεκτικός. Λάτρης της ζωής, των ανθρώπων και των υλικών ανέσεων.
    Απολαμβάνει τη συνεργασία με άλλους. Φέρτε την κοινή λογική και μια ρεαλιστική προσέγγιση στο δουλεία του,
    και να είστε σίγουρος ότι η δουλειά θα γίνει διασκεδαστική.
    Ευέλικτος και αυθόρμητος, προσαρμόζεται εύκολα με νέους ανθρώπους και περιβάλλοντα.
    Μαθαίνει καλύτερα μια νέα δεξιότητα δοκιμάζοντάς τη με άλλους ανθρώπους.
  ENFP:
    Χαρακτήρας ζεστός με ενθουσιασμό και φαντασία. Βλέπει τη ζωή ως γεμάτη ευκαιρίες.
    Κάνει συνδέσεις μεταξύ γεγονότων και πληροφοριών πολύ γρήγορα με αποτέλεσμα να του δίνει αυτοπεποίθηση στο να προχωράει στη ζωή.
    Χρειάζεται πολλή επιβεβαίωση από τους άλλους, εκτιμά εύκολα και υποστηρίζει τους ανθρώπους γύρο του.
    Αυθόρμητος και ευέλικτος, συχνά βασίζεται στην ικανότητά του να αυτοσχεδιάζει και στην προφορική του ευχέρεια.
  ENTP:
    Χαρακτήρας πολύστροφος, με ζωντάνια και δεν κρύβει λόγια. Ικανοποιητικός στην επίλυση νέων και δύσκολων προβλημάτων.
    Καλός στο να καταλαβαίνει τους άλλους ανθρώπους. Η ρουτίνα τον κουράζει, σπάνια θα κάνει το ίδιο πράγμα με τον ίδιο τρόπο,
    ικανός να αλλάζει τη μία δουλειά μετά την άλλη.
  ESTJ:
    Χαρακτήρας πρακτικός, ρεαλιστικός, πραγματικός. Αποφασιστικός, κινείται γρήγορα για να εφαρμόσει τις αποφάσεις και ιδέες που έχει.
    Οργανώνει καταστάσεις και ανθρώπους για να εκπληρωθούν τα σχέδια που θέλει,
    εστιάζεται στο να έχει αποτελέσματα με τον καλύτερο δυνατό τρόπο.
    Έχει ένα σύνολο γενικών λογικών κανόνων, που τους ακολουθάει συστηματικά και θέλει και απο τους άλλους να κάνουν το ίδιο.
    Καταφέρνει να εφαρμόζει τα σχέδιά του.
  ESFJ:
    Χαρακτήρας ευτυχισμένος, ευσυνείδητος και συνεργάσιμος. Θέλει να έχει αρμονία στο περιβάλλον του,
    δουλεύει σκληρά για να το επιτύχει. Θέλει να συνεργάζεται με άλλους για να ολοκληρώνει τις εργασίες με ακρίβεια και γρηγοράδα.
    Πιστός, ακολουθεί κανόνες ακόμα και σε μικρά θέματα. Παρατηρεί τι χρειάζονται οι άλλοι στις ζωές τους
    και προσπαθεί να το προσφέρει. Θέλει να εκτιμάται για το ποιος είναι και για το τι συνεισφέρει.
  ENFJ:
    Χαρακτήρας ζεστός, ευαίσθητος και υπεύθυνος. Εξαιρετικά προσαρμοστικός στα συναισθήματα,
    τις ανάγκες και τα κίνητρα των άλλων. Βλέπει το ποτήρι μισο-γεμάτο, θέλει να βοηθάει τους άλλους.
    Μπορεί να λειτουργεί ως καταλύτης για ατομική και ομαδική ανάπτυξη. Αληθινός, ανταποκρίνεται στον έπαινο και την κριτική.
    Συνεργάσιμος, διευκολύνει τους άλλους σε μια ομάδα και παρέχει έμπνευση.
  ENTJ:
    Χαρακτήρας αποφασιστικός, αναλαμβάνει εύκολα την ηγεσία. Βλέπει γρήγορα παράλογες και αναποτελεσματικές διαδικασίες και πολιτικές,
    αναπτύσσει και εφαρμόζει ολοκληρωμένα συστήματα για την επίλυση οργανωτικών προβλημάτων.
    Απολαμβάνει τον μακροπρόθεσμο προγραμματισμό και την επίλυση στόχων. Συνήθως είναι καλά ενημερωμένος,
    καλά διαβασμένος, απολαμβάνει την επέκταση των γνώσεών του και τη μετάδοση της σε άλλους. Ισχυρογνώμων.
